# Generated by Django 5.1 on 2024-08-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_title_description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
