# Generated by Django 5.1 on 2024-08-26 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_product_title_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='custom_badge',
            field=models.CharField(blank=True, default='', max_length=6, null=True),
        ),
    ]
