# Generated by Django 5.0.2 on 2024-11-15 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='updated_at',
        ),
    ]
