# Generated by Django 5.0.2 on 2024-12-03 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_remove_payment_timestamp_alter_payment_profile'),
        ('store', '0016_remove_category_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
